.github/workflow/test.yml

feat(workflow): add workflow

---

public/index.html

feat(new site): new site

---

.github/workflows/gh-pages.yml

fix(branch): fix branch

---

config/_default/config.toml

feat(issue): add issue

---

content/about.md

feat(about): add about

---

config/_default/config.toml

fix(confi): uncomment

---

config/_default/config.toml

fix(enabkle): fix enable

---

config/_default/config.toml
config/_default/params.toml

fix(params): fix params

---

config/_default/config.toml
config/_default/languages.en.toml
content/about.md
content/posts/_index.md

feat(email): fix email

---

config/_default/params.toml
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Eighth_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Fifth_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/First_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Fourth_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Ninth_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Second_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Seventh_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Sixth_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Tenth_experiment.md
content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Third_experiment.md
layouts/partials/comments.html

feat(comments): add comment

---

layouts/partials/comments.html

feat(comment): add comments

---

content/posts/HDU-Computer-Organization-And-Architecture-Experiment/Tenth_experiment.md

fix(tenth_experiment.md): fix Tenth_experiment.md

---

content/posts/Hugo/hugo-error.md

feat(hugo-error.md): add hugo-error.md

---

config/_default/params.toml

feat(switch): add switch

---

config/_default/config.toml
content/posts/Git/Git.md

feat(crawl): add crawl

---

config/_default/config.toml
static/google54e100ee486bbe48.html

feat(static): add stati

---

google54e100ee486bbe48.html

feat(google): add google

---

static/google54e100ee486bbe48.html

chore(static): delete static

---

content/posts/solidity/first_app.md
content/posts/solidity/hello_world.md
go.mod
go.sum

feat(first_app.md): add first_app.md

---

content/posts/solidity/first_app.md
content/posts/solidity/hello_world.md

update hello_world.md and first_app.md

docs(hello_world.md): update hello_world.md and first_app.md

---

content/posts/git/git.md
content/posts/solidity/first_app.md
content/posts/solidity/hello_world.md
content/posts/solidity/primitives.md
content/posts/solidity/variables.md

add variables.md , update first_app.md,hello_world.md and primitives.md

feat(variables.md): add variables.md , update first_app.md,hello_world.md and primitives.md

---

config/_default/languages.en.toml

refactor(languages.en.toml): fix copyright

---

content/posts/solidity/constants.md

feat(constants.md): add constants.md

---

content/posts/solidity/immutable.md
go.mod
go.sum

feat(immutable.md): add immutable.md

---

content/posts/solidity/constants.md
content/posts/solidity/ether_and_wei.md
content/posts/solidity/first_app.md
content/posts/solidity/hello_world.md
content/posts/solidity/immutable.md
content/posts/solidity/primitives.md
content/posts/solidity/variables.md

feat(ether_and_wei.md): add ether_and_wei.md

---

content/posts/solidity/time.md

docs(time.md): fix url

---

content/posts/solidity/gas_and_gas_price.md

docs(gas_and_gas_price.md): update gas_and_gas_price.md

---

content/posts/golang/go_module.md

feat(go_module.md):add go_module.md

---

content/posts/go_code_comment_standard/go_code_comment_standard.md

add go_code_comment_standard.md

feat(go_code_comment_standard.md): add go_code_comment_standard.md

---

config/_default/menus.en.toml
content/blogs/solidity/first_app.md

update first_app.md and update menus

feat(menus,first_app.md): update first_app.md

---

content/blogs/go/print_value.md
go.mod
go.sum

feat(print-value): add print-value description

---

content/blogs/solidity/001.hello_world.md
content/blogs/solidity/002.first_app.md
content/blogs/solidity/003.value_type.md
content/blogs/solidity/004.variables.md
content/blogs/solidity/005.constants.md
content/blogs/solidity/006.immutable.md
content/blogs/solidity/007.ether_units.md
content/blogs/solidity/008.time_units.md
content/blogs/solidity/009.gas_and_gas_price.md

feat(bg): add solidity bg

---

content/blogs/solidity/010.mapping.md

feat(010.mapping): add 010.mapping

---

content/blogs/solidity/011.structs.md

feat(011.structs.md): add 011

---

content/blogs/solidity/003.value_type.md
content/blogs/solidity/010.mapping.md
content/blogs/solidity/011.structs.md

docs(solidity): fix content error

---

content/projects/ComfyUIClient.md
content/projects/HDU-Computer-Organization-And-Architecture-Experiment.md
content/projects/HDU-computer-organization.md
content/projects/Solidity-Learning.md
content/projects/flt-withdraw.md

feat(projects): update projects
